modLoader="javafml"
loaderVersion="[52,)"
license="All Rights Reserved"

[[mods]]
modId="axmed555_visuals"
version="1.0.0"
displayName="Visuals by axmed555"
description='Visual effects mod with trails, hitboxes and custom effects'
authors="axmed555"

[[dependencies.axmed555_visuals]]
modId="forge"
mandatory=true
versionRange="[52.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.axmed555_visuals]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
